# Generated by Django 4.0.3 on 2022-03-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Fluid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
