# Generated by Django 4.0.3 on 2022-03-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_character_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powers', models.CharField(max_length=100)),
            ],
        ),
    ]
