# Generated by Django 4.0.3 on 2022-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_characterpowers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterpowers',
            old_name='powers',
            new_name='characterpowers',
        ),
        migrations.AddField(
            model_name='character',
            name='CharacterPowers',
            field=models.ManyToManyField(to='main_app.characterpowers'),
        ),
    ]
