# Generated by Django 4.0.3 on 2022-03-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_powers_characterpowers_characterpowers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='CharacterPowers',
            new_name='characterpowers',
        ),
    ]
